### ISSUE TITLE
Not working for latest YouTube version

### ISSUE THREAD

**Issue by jivanirutvik** [Xposed-Modules-Repo/ma.wanam.youtubeadaway#1]
Working fine for YouTube version 17.40.40 but
Didn't work for YouTube version 17.41.36

**Comment by wanam** [comment]
17.41.XX are beta versions, I will check them later.

**Comment by jivanirutvik** [comment]
> 

Okay, thanks

**Comment by wanam** [comment]
Keep it open, I will check it soon.
