### ISSUE TITLE
Background issue 

### ISSUE THREAD

**Issue by Nicolas22320** [Xposed-Modules-Repo/ma.wanam.youtubeadaway#3]
Hi, background dont work anymore

YT beta: 17.43.35
[LSPosed_2022-10-28T13_46_25.771001.zip](https://github.com/Xposed-Modules-Repo/ma.wanam.youtubeadaway/files/9888093/LSPosed_2022-10-28T13_46_25.771001.zip)

**Comment by wanam** [comment]
@Nicolas22320 Thanks for the logs, unfortunately I cannot take a look in the meantime, I'm out for 2 weeks with a limited access to my pc.

Will take a look when I come back.

**Comment by wanam** [comment]
Fixed on https://github.com/Xposed-Modules-Repo/ma.wanam.youtubeadaway/commit/c3d82542e05029b93201ca8facc81a67d0903b7d
